name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Permet de lancer manuellement aussi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Scala and Java
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "openjdk@1.11.0"

      - name: Build and Test with SBT
        run: |
          sbt clean compile test assembly

      - name: Verify JAR Exists
        run: ls -lh target/scala-2.12/

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: traffic-weather-jar
          path: target/scala-2.12/TrafficWeatherAnalytics-assembly-0.1.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Attend que le job build soit terminé avec succès

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: traffic-weather-jar

      - name: Install Databricks CLI
        run: |
          pip install --upgrade databricks-cli

      - name: Upload JAR to Databricks
        run: |
          export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}

          echo "Uploading JAR to Databricks DBFS..."
          databricks fs cp TrafficWeatherAnalytics-assembly-0.1.jar dbfs:/FileStore/jars/TrafficWeatherAnalytics-assembly-0.1.jar --overwrite